// <auto-generated>
//   This code file has automatically been added by the "BUTR.CrashReport.Bannerlord.Source" NuGet package (https://www.nuget.org/packages/BUTR.CrashReport.Bannerlord.Source).
//   Please see https://github.com/BUTR/BUTR.CrashReport for more information.
//
//   IMPORTANT:
//   DO NOT DELETE THIS FILE if you are using a "packages.config" file to manage your NuGet references.
//   Consider migrating to PackageReferences instead:
//   https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference
//   Migrating brings the following benefits:
//   * The "BUTR.CrashReport.Bannerlord.Source" folder and the "CrashReportCreator.cs" file don't appear in your project.
//   * The added file is immutable and can therefore not be modified by coincidence.
//   * Updating/Uninstalling the package will work flawlessly.
// </auto-generated>

#region License
// MIT License
//
// Copyright (c) Bannerlord's Unofficial Tools & Resources
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
#endregion

#if !BUTRCRASHREPORT_DISABLE
#nullable enable
#if !BUTRCRASHREPORT_ENABLEWARNINGS
#pragma warning disable
#endif

namespace BUTR.CrashReport.Bannerlord
{
    using global::Bannerlord.BUTR.Shared.Extensions;
    using global::Bannerlord.BUTR.Shared.Helpers;
    using global::Bannerlord.ModuleManager;

    using global::BUTR.CrashReport.Models;

    using global::HarmonyLib;

    using global::System;
    using global::System.Collections.Generic;
    using global::System.Collections.Immutable;
    using global::System.IO;
    using global::System.Linq;
    using global::System.Reflection;
    using global::System.Security.Cryptography;

    internal class CrashReportCreator
    {
        public static CrashReportModel Create(CrashReportInfo crashReport)
        {
            return new CrashReportModel
            {
                Id = crashReport.Id,
                GameVersion = ApplicationVersionHelper.GameVersionStr(),
                Version = crashReport.Version,
                Exception = GetRecursiveException(crashReport.Exception),
                EnhancedStacktrace = GetEnhancedStacktrace(crashReport),
                InvolvedModules = GetInvolvedModuleList(crashReport),
                Modules = GetModuleList(crashReport),
                Assemblies = GetAssemblyList(crashReport),
                HarmonyPatches = GetHarmonyPatchesListHtml(crashReport),
                Metadata = new()
                {
                    LauncherType = GetLauncherType(crashReport),
                    LauncherVersion = GetLauncherVersion(crashReport),

                    Runtime = System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription,

                    AdditionalMetadata = new List<KeyValuePair<string, string>>()
                    {
                        new("BUTRLoaderVersion", GetBUTRLoaderVersion(crashReport)),
                        new("BLSEVersion", GetBLSEVersion(crashReport)),
                        new("LauncherExVersion", GetLauncherExVersion(crashReport)),
                    }
                },
                AdditionalMetadata = new List<KeyValuePair<string, string>>(),
            };
        }

        private static string GetBUTRLoaderVersion(CrashReportInfo crashReport)
        {
            if (crashReport.AvailableAssemblies.FirstOrDefault(x => x.GetName().Name == "Bannerlord.BUTRLoader") is { } bAssembly)
                return bAssembly.GetName().Version?.ToString() ?? string.Empty;
            return string.Empty;
        }
        private static string GetBLSEVersion(CrashReportInfo crashReport)
        {
            var blseMetadata = crashReport.AvailableAssemblies.FirstOrDefault(x => x.GetName().Name == "Bannerlord.BLSE")?.GetCustomAttributes<AssemblyMetadataAttribute>();
            return blseMetadata?.FirstOrDefault(x => x.Key == "BLSEVersion")?.Value ?? string.Empty;
        }
        private static string GetLauncherExVersion(CrashReportInfo crashReport)
        {
            var launcherExMetadata = crashReport.AvailableAssemblies.FirstOrDefault(x => x.GetName().Name == "Bannerlord.LauncherEx")?.GetCustomAttributes<AssemblyMetadataAttribute>();
            return launcherExMetadata?.FirstOrDefault(x => x.Key == "LauncherExVersion")?.Value ?? string.Empty;
        }

        private static string GetLauncherType(CrashReportInfo crashReport)
        {
            if (crashReport.AdditionalMetadata.TryGetValue("Parent_Process_Name", out var parentProcessName))
            {
                return parentProcessName switch
                {
                    "Vortex" => "vortex",
                    "BannerLordLauncher" => "bannerlordlauncher",
                    "steam" => "steam",
                    "GalaxyClient" => "gog",
                    "EpicGamesLauncher" => "epicgames",
                    "devenv" => "debuggervisualstudio",
                    "JetBrains.Debugger.Worker64c" => "debuggerjetbrains",
                    "explorer" => "explorer",
                    "NovusLauncher" => "novus",
                    "ModOrganizer" => "modorganizer",
                    _ => $"unknown launcher - {parentProcessName}"
                };
            }

            if (!string.IsNullOrEmpty(GetBUTRLoaderVersion(crashReport)))
                return "butrloader";

            return "vanilla";
        }

        private static string GetLauncherVersion(CrashReportInfo crashReport)
        {
            if (crashReport.AdditionalMetadata.TryGetValue("Parent_Process_File_Version", out var parentProcessFileVersion))
                return parentProcessFileVersion;

            if (GetBUTRLoaderVersion(crashReport) is { } bVersion && !string.IsNullOrEmpty(bVersion))
                return bVersion;

            return "0";
        }

        private static ExceptionModel GetRecursiveException(Exception ex)
        {
            return new()
            {
                Type = ex.GetType().FullName!,
                Message = ex.Message,
                Source = ex.Source,
                CallStack = ex.StackTrace,
                InnerException = ex.InnerException is not null ? GetRecursiveException(ex.InnerException) : null,
            };
        }

        private static ICollection<EnhancedStacktraceFrameModel> GetEnhancedStacktrace(CrashReportInfo crashReport)
        {
            var builder = ImmutableArray.CreateBuilder<EnhancedStacktraceFrameModel>();
            foreach (var stacktrace in crashReport.Stacktrace.GroupBy(x => x.StackFrameDescription))
            {
                foreach (var entry in stacktrace)
                {
                    var methodsBuilder = ImmutableArray.CreateBuilder<EnhancedStacktraceFrameMethod>();
                    foreach (var method in entry.Methods)
                    {
                        methodsBuilder.Add(new()
                        {
                            Module = method.ModuleInfo is null ? "UNKNOWN" : method.ModuleInfo.Id,
                            Method = method.Method.DeclaringType is not null ? $"{method.Method.DeclaringType.FullName}.{method.Method.Name}" : method.Method.Name,
                            MethodFullName = method.Method.FullDescription(),
                            MethodParameters = method.Method.GetParameters().Select(x => x.ParameterType.FullName).ToArray(),
                            CilInstructions = method.CilInstructions,
                        });
                    }

                    builder.Add(new()
                    {
                        Name = stacktrace.Key,
                        FrameDescription = entry.StackFrameDescription,
                        OriginalMethod = new()
                        {
                            Module = entry.ModuleInfo is null ? "UNKNOWN" : entry.ModuleInfo.Id,
                            Method = entry.Method.DeclaringType is not null ? $"{entry.Method.DeclaringType.FullName}.{entry.Method.Name}" : entry.Method.Name,
                            MethodFullName = entry.Method.FullDescription(),
                            MethodParameters = entry.Method.GetParameters().Select(x => x.ParameterType.FullName).ToArray(),
                            CilInstructions = entry.CilInstructions,
                        },
                        PatchMethods = methodsBuilder.ToArray(),
                        ILOffset = entry.ILOffset,
                        MethodFromStackframeIssue = entry.MethodFromStackframeIssue,
                    });
                }
            }
            return builder.ToArray();
        }

        private static ICollection<InvolvedModuleModel> GetInvolvedModuleList(CrashReportInfo crashReport)
        {
            var builder = ImmutableArray.CreateBuilder<InvolvedModuleModel>();
            foreach (var stacktrace in crashReport.FilteredStacktrace.GroupBy(m => m.ModuleInfo))
            {
                var module = stacktrace.Key;
                if (module is null) continue;

                builder.Add(new()
                {
                    Id = module.Id,
                    Stacktrace = string.Join(Environment.NewLine, stacktrace.Select(x => x.Method.FullDescription())),
                    AdditionalMetadata = new List<KeyValuePair<string, string>>(),
                });
            }
            return builder.ToArray();
        }

        private static ICollection<ModuleModel> GetModuleList(CrashReportInfo crashReport)
        {
            var builder = ImmutableArray.CreateBuilder<ModuleModel>();

            foreach (var module in crashReport.LoadedModules.OfType<ModuleInfo>().Select(x => x.InternalModuleInfo))
            {
                var isManagedByVortex = File.Exists(Path.Combine(module.Path, "__folder_managed_by_vortex"));

                builder.Add(new ModuleModel
                {
                    Id = module.Id,
                    Name = module.Name,
                    Version = module.Version.ToString(),
                    IsExternal = module.IsExternal,
                    IsOfficial = module.IsOfficial,
                    IsSingleplayer = module.IsSingleplayerModule,
                    IsMultiplayer = module.IsMultiplayerModule,
                    Url = module.Url,
                    DependencyMetadatas = module.DependenciesAllDistinct().Select(x => new ModuleDependencyMetadataModel
                    {
                        ModuleId = x.Id,
                        Type = (ModuleDependencyMetadataModelType) x.LoadType,
                        IsOptional = x.IsOptional,
                        IsIncompatible = x.IsIncompatible,
                        Version = x.Version.ToString(),
                        VersionRange = x.VersionRange.ToString(),
                        AdditionalMetadata = new List<KeyValuePair<string, string>>(),
                    }).ToArray(),
                    SubModules = module.SubModules.Where(ModuleInfoHelper.CheckIfSubModuleCanBeLoaded).Select(x => new ModuleSubModuleModel
                    {
                        Name = x.Name,
                        AssemblyName = x.DLLName,
                        Entrypoint = x.SubModuleClassType,
                        AdditionalMetadata = x.Assemblies.Select(y => new KeyValuePair<string, string>("METADATA:Assembly", y))
                            .Concat(x.Tags.SelectMany(y => y.Value.Select(z => new KeyValuePair<string, string>(y.Key, z))))
                            .ToArray(),
                    }).ToArray(),
                    AdditionalMetadata = new List<KeyValuePair<string, string>>()
                    {
                        new("METADATA:MANAGED_BY_VORTEX", isManagedByVortex.ToString()),
                    },
                });
            }

            return builder.ToArray();
        }

        private static ICollection<AssemblyModel> GetAssemblyList(CrashReportInfo crashReport)
        {
            static string CalculateMD5(string filename)
            {
                using var md5 = MD5.Create();
                using var stream = File.OpenRead(filename);
                var hash = md5.ComputeHash(stream);
                return BitConverter.ToString(hash).Replace("-", "").ToLowerInvariant();
            }

            var builder = ImmutableArray.CreateBuilder<AssemblyModel>();

            foreach (var assembly in crashReport.AvailableAssemblies)
            {
                string? moduleId = null;
                foreach (var loadedModule in crashReport.LoadedModules.OfType<ModuleInfo>().Select(x => x.InternalModuleInfo))
                {
                    if (ModuleInfoHelper.IsModuleAssembly(loadedModule, assembly))
                    {
                        moduleId = loadedModule.Id;
                        break;
                    }
                }

                // TODO:
                var isTWCore = !assembly.IsDynamic && assembly.Location.IndexOf(@"Mount & Blade II Bannerlord\bin\", StringComparison.InvariantCultureIgnoreCase) >= 0;
                var isSystem = !assembly.IsDynamic && assembly.Location.IndexOf(@"Windows\Microsoft.NET\", StringComparison.InvariantCultureIgnoreCase) >= 0;

                var assemblyName = assembly.GetName();

                builder.Add(new()
                {
                    Name = assemblyName.Name,
                    FullName = assembly.ToString(),
                    Version = assemblyName.Version.ToString(),
                    Architecture = assemblyName.ProcessorArchitecture.ToString(),
                    Hash = assembly.IsDynamic || string.IsNullOrWhiteSpace(assembly.Location) || !File.Exists(assembly.Location) ? "" : CalculateMD5(assembly.Location),
                    Path = assembly.IsDynamic ? "DYNAMIC" : string.IsNullOrWhiteSpace(assembly.Location) ? "EMPTY" : !File.Exists(assembly.Location) ? "MISSING" : assembly.Location,
                    IsDynamic = assembly.IsDynamic,
                    Type = moduleId is not null ? AssemblyModelType.Module : isTWCore ? AssemblyModelType.GameCore : isSystem ? AssemblyModelType.System : AssemblyModelType.Unclassified,
                    ModuleId = moduleId,
                    SubModuleId = "",
                    AdditionalMetadata = new List<KeyValuePair<string, string>>()
                    {
                        new("METADATA:IS_TW", isTWCore.ToString()),
                        new("METADATA:IS_SYSTEM", isSystem.ToString()),
                    },
                });
            }

            return builder.ToArray();
        }

        private static ICollection<HarmonyPatchesModel> GetHarmonyPatchesListHtml(CrashReportInfo crashReport)
        {
            var builder = ImmutableArray.CreateBuilder<HarmonyPatchesModel>();

            static void AppendPatches(ImmutableArray<HarmonyPatchModel>.Builder builder, HarmonyPatchModelType type, IEnumerable<Patch> patches)
            {
                foreach (var patch in patches)
                {
                    builder.Add(new()
                    {
                        Owner = patch.owner,
                        Namespace = $"{patch.PatchMethod.DeclaringType!.FullName}.{patch.PatchMethod.Name}",
                        Index = patch.index,
                        Priority = patch.priority,
                        Before = patch.before.ToArray(),
                        After = patch.after.ToArray(),
                        Type = type,
                    });
                }
            }

            foreach (var (originalMethod, patches) in crashReport.LoadedHarmonyPatches)
            {
                var prefixBuilder = ImmutableArray.CreateBuilder<HarmonyPatchModel>();
                var postfixBuilder = ImmutableArray.CreateBuilder<HarmonyPatchModel>();
                var finalizerBuilder = ImmutableArray.CreateBuilder<HarmonyPatchModel>();
                var transpilerBuilder = ImmutableArray.CreateBuilder<HarmonyPatchModel>();

                AppendPatches(prefixBuilder, HarmonyPatchModelType.Prefix, patches.Prefixes);
                AppendPatches(postfixBuilder, HarmonyPatchModelType.Postfix, patches.Postfixes);
                AppendPatches(finalizerBuilder, HarmonyPatchModelType.Finalizer, patches.Finalizers);
                AppendPatches(transpilerBuilder, HarmonyPatchModelType.Transpiler, patches.Transpilers);

                if (prefixBuilder.Count > 0 || postfixBuilder.Count > 0 || finalizerBuilder.Count > 0 || transpilerBuilder.Count > 0)
                {
                    builder.Add(new()
                    {
                        OriginalMethod = originalMethod.Name,
                        OriginalMethodFullName = $"{originalMethod.DeclaringType?.FullName}.{originalMethod.Name}",
                        Prefixes = prefixBuilder.ToArray(),
                        Postfixes = postfixBuilder.ToArray(),
                        Finalizers = finalizerBuilder.ToArray(),
                        Transpilers = transpilerBuilder.ToArray(),
                    });
                }
            }

            return builder.ToArray();
        }
    }
}

#pragma warning restore
#nullable restore
#endif // BUTRCRASHREPORT_DISABLE