name: Deploy WASM

on:
  workflow_dispatch:
  workflow_run: 
    workflows: ["Publish WASM"]
    types:
      - completed

jobs:
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    environment:
        name: netlify
        url: ${{ steps.deploy.outputs.deploy-url }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Deploy to Netlify
        id: deploy
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './wwwroot'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
